name: Build and Release Mod

on:
  push:
    tags:
      - 'v*'   # Only run when you push a tag like v1.0, v1.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 8
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      # Step 3: Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Step 4: Build the mod
      - name: Build mod
        run: ./gradlew build

      # Step 5: Upload JAR as release asset
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
